server:
  port: 19999
spring:
  application:
    name: tiny-id
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tiny_id?useSSL=false&autoReconnect=true&characterEncoding=utf8
    username: root
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource

batch:
  size:
    max: 1000
